export const SMR_PREFIX = "simplecontainer.io/v1"
export const SMR_ENDPOINT_NAME = "node"
export const SMR_NODE_DOMAIN = "node.private"
export const SMR_LOCAL_DOMAIN = "private"

export const PLATFORM_DOCKER = "docker"
export const PLATFORM_MOCKER = "mocker"

export const CATEGORY_KIND = "kind"
export const CATEGORY_STATE = "state"
export const CATEGORY_ETCD = "etcd"
export const CATEGORY_PLAIN = "plain"
export const CATEGORY_EVENT = "event"
export const CATEGORY_SECRET = "secret"
export const CATEGORY_DNS = "dns"
export const CATEGORY_INVALID = "invalid"

export const SIGTERM = "SIGTERM"
export const SIGKILL = "SIGKILL"

export const KIND_NODE = "node"
export const KIND_CONTAINER = "container"
export const KIND_CONTAINERS = "containers"
export const KIND_CONFIGURATION = "configuration"
export const KIND_RESOURCE = "resource"
export const KIND_CERTKEY = "certkey"
export const KIND_HTTPAUTH = "httpauth"
export const KIND_GITOPS = "gitops"
export const KIND_NETWORK = "network"
export const KIND_SECRET = "secret"
export const KIND_CUSTOM = "custom"

export const REMOVE_KIND = "remove"

export const STATUS_RESPONSE_SCHEDULED = "action accepted and scheduled for action"
export const STATUS_RESPONSE_APPLIED = "object is applied"
export const STATUS_RESPONSE_BAD_REQUEST = "request sent is invalid"
export const STATUS_RESPONSE_DELETED = "object is deleted"
export const STATUS_RESPONSE_RESTART = "object is restarted"
export const STATUS_RESPONSE_REFRESHED = "object is refreshed"
export const STATUS_RESPONSE_SYNCED = "object is synced"
export const STATUS_RESPONSE_NOT_FOUND = "object is not found"
export const STATUS_RESPONSE_INTERNAL_ERROR = "object action errored on the server"
